name: mypy
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '^3.8.0'
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install tox
    - name: Tox
      run: 'tox -e mypy'
